version: '3.7'

services:
  umami:
    container_name: armadietto
    image: remotestorage/armadietto-monolithic:latest
    ports:
      - '${APP_PORT}:8000'
    restart: unless-stopped
    networks:
      - tipi_main_network
    labels:
      # Main
      traefik.enable: true
      traefik.http.middlewares.umami-web-redirect.redirectscheme.scheme: https
      traefik.http.services.umami.loadbalancer.server.port: 8000
      # Web
      traefik.http.routers.umami-insecure.rule: Host(`${APP_DOMAIN}`)
      traefik.http.routers.umami-insecure.entrypoints: web
      traefik.http.routers.umami-insecure.service: armadietto
      traefik.http.routers.umami-insecure.middlewares: armadietto-web-redirect
      # Websecure
      traefik.http.routers.umami.rule: Host(`${APP_DOMAIN}`)
      traefik.http.routers.umami.entrypoints: websecure
      traefik.http.routers.umami.service: armadietto
      traefik.http.routers.umami.tls.certresolver: myresolver
      # Local domain
      traefik.http.routers.umami-local-insecure.rule: Host(`armadietto.${LOCAL_DOMAIN}`)
      traefik.http.routers.umami-local-insecure.entrypoints: web
      traefik.http.routers.umami-local-insecure.service: armadietto
      traefik.http.routers.umami-local-insecure.middlewares: armadietto-web-redirect
      # Local domain secure
      traefik.http.routers.umami-local.rule: Host(`armadietto.${LOCAL_DOMAIN}`)
      traefik.http.routers.umami-local.entrypoints: websecure
      traefik.http.routers.umami-local.service: armadietto
      traefik.http.routers.umami-local.tls: true
      runtipi.managed: true
